### ISSUE TITLE
[copyright infringement] please rename your packages and organisation on github

### ISSUE THREAD

**Issue by nicolas-grekas** [symfonyboot/symfonyboot-bundle#7]
Hello,

Naming your organization and your packages symfonyboot is going to create confusion for the community.

Also Symfony is a trademark that must be used within the policy described at https://symfony.com/trademark

Please rename your organization and all related packages.

Thanks for your understanding.

**Comment by silasyudi** [comment]
Hello Nicolas

I understand your position and I will rename this project. I apologize for any trouble it has caused.

**Comment by silasyudi** [comment]
Hi Nicolas, I sent this project to my personal namespace for fix this copyright issue. Thanks for your patience.
